### ISSUE TITLE
Executables scripts cannot be run directly in the Docker image

### ISSUE THREAD

**Issue by dclong** [notebooks-ai/notebooks-help#10]
For example, Shell/Python scripts cannot be run even I make them runnable by `chmod +x`.

**Comment by martinzugnoni** [comment]
Try executing the script by calling the interpreter manually, like this:

```
$ python hello.py
```

instead of this:

```
$ ./hello.py
```

Same applies for Shell/Bash scripts, of course changing the interpreter:

```
$ bash hello.sh
```

**Comment by dclong** [comment]
I do know that we can run scripts in this way, but it's rather inconvenient.

**Comment by santiagobasulto** [comment]
What would be another way of running them @dclong ?

**Comment by dclong** [comment]
@santiagobasulto Sorry for the confusion. By "the Shebang way" I mean have `#!/bin/bash` etc. in the first line of a file, make the file executable and run it using `./hello.sh`. It's the exactly the first way we talked about above.

**Comment by santiagobasulto** [comment]
We hadn't realized that it wasn't possible to do `./hello.sh` before 😱 . Thanks for the report, we'll fix it.

**Comment by dclong** [comment]
Any update?

**Comment by dclong** [comment]
Seems that this issue has been fixed.
