### ISSUE TITLE
Persist user's home directory

### ISSUE THREAD

**Issue by dclong** [notebooks-ai/notebooks-help#11]
By mounting the save directory similar to the /app directory.

**Comment by santiagobasulto** [comment]
Thanks @dclong!

**Comment by dclong** [comment]
@santiagobasulto FYI, https://github.com/gitpod-io/gitpod/issues/340

**Comment by santiagobasulto** [comment]
This is a great idea @dclong. We won't be implementing it soon, but I'm labeling it to revisit it in the following sprints.
