### ISSUE TITLE
Landing Page Redirect

### ISSUE THREAD

**Issue by jwinf843** [notebooks-ai/notebooks-help#12]
Would it be possible to change the default landing page if we're already signed in? 

If I go to Notebooks.ai and am already signed in, I should automatically be redirected to the dashboard page.

**Comment by santiagobasulto** [comment]
@jwinf843 will assign this for discussion, thanks for the feedback.

**Comment by matiascaputti** [comment]
@jwinf843 Now if you're signed in, you'll be directly redirected to your dashboard.
