### ISSUE TITLE
Future Request - Folder

### ISSUE THREAD

**Issue by okurtphed** [notebooks-ai/notebooks-help#14]
Sometimes it is useful to put different projects into the same folder. I am sorry if this is already available but I just couldn't find out 😅

**Comment by santiagobasulto** [comment]
Hello @okurtphed! What do you mean by this? You can already put multiple folders in the same project. You can't however group multiple projects.

**Comment by okurtphed** [comment]
Hi @santiagobasulto , yes I actually think being able to put different projects on the same folder (or another way of grouping) can be useful. For example, I would like to keep my rmotr projects on the same folder, so that they will be separated from my other personal projects. This may help for a cleaner home page.

Just a thought :)

**Comment by santiagobasulto** [comment]
It is a good idea indeed @okurtphed! Thanks for sharing. It won't make it to this milestone, but we'll keep it in the backlog. I'd like to gather more use case examples from other users.
