### ISSUE TITLE
An internal error ocurred, please try again later.

### ISSUE THREAD

**Issue by selmabensaid** [notebooks-ai/notebooks-help#15]
I am getting this error message when I try to login:
'An internal error ocurred, please try again later.'

**Comment by martinzugnoni** [comment]
Hello @selmabensaid. Do you already have an account and it's now failing when you want to login again? Or is it the first time you access?

**Comment by selmabensaid** [comment]
I already have account. I'm trying to login for the first time from a different computer.

**Comment by martinzugnoni** [comment]
Can you point me to your notebooks.ai username so I can investigate if there's any wrong?

**Comment by selmabensaid** [comment]
selmabensaid@hotmail.com

**Comment by martinzugnoni** [comment]
The account status looks correct. Is there any way you could provide a screenshot of the error? Thank you

**Comment by selmabensaid** [comment]
![image](https://user-images.githubusercontent.com/47462308/57235128-cd0fbd00-6fe7-11e9-95ad-e731724fe567.png)

**Comment by martinzugnoni** [comment]
Can you please check in the browser developers console to see if the login request gives us more information about what's going wrong? Maybe there's a more clear error message there. Thank you.

**Comment by selmabensaid** [comment]
![image](https://user-images.githubusercontent.com/47462308/57236640-2d542e00-6feb-11e9-9032-00da3426061e.png)

**Comment by martinzugnoni** [comment]
By any chance are you inside a VPN or some sort of restricted access network? Because it seems that Google and Sentry requests are also failing.

**Comment by selmabensaid** [comment]
Yes I am on a restricted network but I contacted the company's support and they said that is the notebook.ai is not restricted since the page is loading. Is it a security issue?

**Comment by martinzugnoni** [comment]
That makes more sense now. Note that the authentication is happening in the API side, which has a different domain (api.notebooks.ai), maybe this domain is being blocked?

**Comment by selmabensaid** [comment]
yes the api.notebooks.ai domain is blocked. I understand now. Thank you for your help.

**Comment by martinzugnoni** [comment]
Welcome!
