### ISSUE TITLE
"Open lab" button missing when project is already forked

### ISSUE THREAD

**Issue by santiagobasulto** [notebooks-ai/notebooks-help#19]
![image](https://user-images.githubusercontent.com/872296/59931423-4b4ee400-941b-11e9-91eb-ac8dce9c4e55.png)

**Comment by matiascaputti** [comment]
If you already forked a project you'll see the "Open lab" button.

![Screen Shot 2019-10-03 at 4 37 26 PM](https://user-images.githubusercontent.com/7065401/66158388-25c99d00-e5fc-11e9-9dd2-3659edd86706.png)
