### ISSUE TITLE
Installing fbprophet 

### ISSUE THREAD

**Issue by mryap** [notebooks-ai/notebooks-help#2]
![image](https://user-images.githubusercontent.com/15719191/50594136-36918a80-0e93-11e9-94ac-ce55996579fe.png)

I seems to have problem installing fbprophet in your environment. 

I got a `Could not install packages due to an EnvironmentError:[Errno12] Cannot Allocate Memroy`

Thanks

**Comment by martinzugnoni** [comment]
Hello @mryap, thanks for your ticket. I will take a look. The library might be too memory-hungry for the size of the containers.

**Comment by mryap** [comment]
hi @martinzugnoni, I create a new project on my account Dashboard and the issues goes away. 

https://i4-p35571.proxy.rmotr.com/lab/workspaces/preview

**Comment by martinzugnoni** [comment]
Then maybe your environment was already loaded with too much data in memory, and the remaining memory was not enough to install the library. 

You could try "Turn off" the project (from your dashboard), that will restart the container and free unnecessary memory, and opening the project again. 

Let me know if this helps.

**Comment by santiagobasulto** [comment]
This was only a memory issue. We've increased the resources of all our projects lately, shouldn't be a problem now.
