### ISSUE TITLE
Clicking "NOTEBOOKS_" in the corner should open a new tab

### ISSUE THREAD

**Issue by jwinf843** [notebooks-ai/notebooks-help#24]
When I click the "NOTEBOOKS_" button in the corner, it should direct me to my dashboard in a new tab instead of taking me directly from in current workspace tab. This is doubly-true because for some reason middle-click (click to open in new tab) doesn't work on this link.

**Comment by martinzugnoni** [comment]
Good point, @jwinf843 👍
