### ISSUE TITLE
Requirements don't seem to be installed

### ISSUE THREAD

**Issue by syclops** [notebooks-ai/notebooks-help#28]
I am trying to set up a clone of the [ModSimPy](https://github.com/AllenDowney/ModSimPy) repo.

As I could not find a way to import an `environment.yml` file, I added the packages listed in the [repo environment file](https://github.com/AllenDowney/ModSimPy/blob/master/environment.yml) to the Requirements section of the project.

When I tried importing modules in a new or existing notebook, I found that three imports were not working: `pint`, `tables`, and `modsim`. It seems that `modsim` did not work due to the lack of Pint in a new notebook, but in an existing notebook from the repo, it did not work at all.

The workaround to this is to open a terminal and use `pip` to install the missing packages, but this seems a bit clunky. Additionally, I'm considering using this platform for teaching, and it doesn't seem ideal to have students do this workaround themselves.

Is there something else I need to do to make sure that the right packages are installed upon launch?

**Comment by martinzugnoni** [comment]
Hello @syclops, thanks for reporting. We will take a closer look at the problem and come back to you. If you need any extra help for your teaching activities, don't hesitate to contact us.

**Comment by martinzugnoni** [comment]
@syclops the first thing I noticed is that `pytables>=3.5` is not available in pypi. If you want to install it with `pip` you should use `tables` instead.

This error is probably breaking the whole pip install process and anything else coming after this error won't be installed. I guess this can be the reason of the issue you are experimenting.

Can you please make sure each individual package you have in the project settings can be installed correctly and the version matches one available version in pypi?

Let me know if there're still problems after it.

**Comment by syclops** [comment]
@martinzugnoni it looks like changing to tables does work, thanks.

However, after experimenting a bit, I think that any error in the requirements breaks the *entire* installation, not just the packages that come after it in the list.

I can't verify this directly as I'm not sure what packages are installed in the Data Science kernel. But the clue was that `pint` seemed not to be installed either with `pytables` as a requirement.

I will close the issue as it seems to have been solved, but documentation somewhere that describes what the Data Science kernel includes or what its image is composed of would be fantastic. Thanks!
