### ISSUE TITLE
WebView Not running

### ISSUE THREAD

**Issue by mryap** [notebooks-ai/notebooks-help#3]
I might have miss something on the site. 

What do I need to enable to avoid seeing this? Thank You 

Does this Webview works like Github's own http://htmlpreview.github.io?

![image](https://user-images.githubusercontent.com/15719191/50666934-e0b20500-0fae-11e9-841e-2f8857905a1f.png)

**Comment by martinzugnoni** [comment]
The "webview" page is suppose to be used with web applications (like Flask, Django, etc) running on port 5000. Do you have the server running on that port in your environment?
