### ISSUE TITLE
Notebooks Disappear

### ISSUE THREAD

**Issue by dankeylon** [notebooks-ai/notebooks-help#36]
I have a project with a few python notebooks.  Recently I started the project back up after a few weeks away and all the notebooks were gone.  After a few hours, they reappeared.  The following morning they again disappeared.

**Comment by martinzugnoni** [comment]
Hello! sorry for the late response. I think the issue is solved now. Please make sure to "Turn off" your project and start it again before checking if the issue is fixed. Thank you.
