### ISSUE TITLE
Unable to use mpl_toolkits.basemap

### ISSUE THREAD

**Issue by sccx** [notebooks-ai/notebooks-help#43]
The Notebook throws the following error when I try to run code that depends on mpl_toolkits.basemap. The code works locally on my Mac OS machine, but not in the notebook.

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-8-90504f491b76> in <module>
      9 import matplotlib
     10 import matplotlib.pyplot as plt
---> 11 from mpl_toolkits.basemap import Basemap
     12 from scipy.stats import circmean
     13 from matplotlib.colors import LogNorm

ModuleNotFoundError: No module named 'mpl_toolkits.basemap'

**Comment by santiagobasulto** [comment]
There are different ways to install this it seems [1](https://stackoverflow.com/questions/40374441/python-basemap-module-impossible-to-import/43234894#43234894), but it's not part of Notebooks.ai

A quick look at [Basemap's repo](https://github.com/matplotlib/basemap) shows this warning:
> **Warning**: this package is being deprecated in favour of cartopy.

To install `cartopy`:

```bash
!apt-get install -y libproj-dev proj-data proj-bin libgeos-dev
!pip install cython
!pip install Cartopy
```

![image](https://user-images.githubusercontent.com/872296/77028142-d2af9080-6976-11ea-9beb-58fc36db379d.png)
