### ISSUE TITLE
conda installation 

### ISSUE THREAD

**Issue by archgen** [notebooks-ai/notebooks-help#44]
Hi, I am testing out NOTEBOOKS_ . Do you have any wiki's on how to install bioconda?

Cheers,
Matt

**Comment by santiagobasulto** [comment]
Hello Matt! We don't support conda for now, we only support pip. BUT! There's a new image for BioPython that you can try out!

<img width="929" alt="Screen Shot 2020-03-18 at 11 36 35 PM" src="https://user-images.githubusercontent.com/872296/77026007-60887d00-6971-11ea-9469-7ccd3773059d.png">
