### ISSUE TITLE
How to install Matplotlib?

### ISSUE THREAD

**Issue by silvioalvim** [notebooks-ai/notebooks-help#45]
How to install Matplotlib for use?

**Comment by santiagobasulto** [comment]
It's already installed in the Data Science image:

<img width="941" alt="Screen Shot 2020-03-05 at 10 48 00 AM" src="https://user-images.githubusercontent.com/872296/75998520-f54d9e00-5ece-11ea-9d73-7fea30da15a4.png">

In other case it's just `pip install matplotlib` from a terminal.
