### ISSUE TITLE
Sharing a Notebook

### ISSUE THREAD

**Issue by MiguelNiblock** [notebooks-ai/notebooks-help#5]
I haven't found documentation on how to actually share a notebook with someone. And this is the feature that led me to find RMOTR in the first place. I've right clicked on the IPYNB file in the browser, but the link seems to require a login token if opened in a different machine. What is someone supposed to do to actually share a notebook in the cloud with a student/ mentor/ collaborator?

**Comment by santiagobasulto** [comment]
Hello Miguel! This feature is experimental, we're testing it internally before it's released. What would be your primary use case? This would help us understand it better.

**Comment by MiguelNiblock** [comment]
Im taking another online course and would like to share notebooks with my mentor in some way other than github, so as to allow him to instantly view and edit my code. This can also be done with google collab but im not a big fan of it.

**Comment by santiagobasulto** [comment]
Ah, I see. Google colab's isn't perfect either, it's just a copy of the underlying notebook without any sort of state. We'll try speeding it up. In the meantime, you could "inspect iframe URL" and share that iframe URL. Out of curiosity, what course are you taking?

**Comment by MiguelNiblock** [comment]
I actually don't like collab. It forces you to use different keyboard shortcuts than classic jupyter, which I believe to be a business strategy more than a technical necessity. 

There's also mybinder.org, which allows you to instantly edit notebooks hosted in github, but changes have to be saved in a separate copy of the notebook, so it's really like working on a copy of the file.

And lastly, the good old nbviewer.jupyter.org, which is read-only.

Im taking a Data Science bootcamp with Thinkful. :) Rmotr looks interesting.

**Comment by santiagobasulto** [comment]
Oh great, I've heard good things about Thinkful's program. Mybinder is a great effort, but yeah, it lacks the one true useful feature that is writing things back after modifying them. 

Feel free to share RMOTR Notebooks with people at Thinkful, we're building it as a universal educational resource.

**Comment by dclong** [comment]
It's even better if real-time collaboration is supported.

**Comment by santiagobasulto** [comment]
Status update: real time collaboration is still very early. I had the chance to meet with core Jupyter developers during PyCon and they don't see it happening anytime soon. We'll of course keep our eyes open.
