### ISSUE TITLE
Please add ability to save themes

### ISSUE THREAD

**Issue by jwinf843** [notebooks-ai/notebooks-help#6]
Please. 

I'm begging you.

**Comment by santiagobasulto** [comment]
Can someone help this man?

**Comment by santiagobasulto** [comment]
@jwinf843 I think this is not technically possible yet. I just left a comment here: https://github.com/jupyterlab/jupyterlab/pull/2759#issuecomment-460255119

**Comment by santiagobasulto** [comment]
Labeled for future releases.
