### ISSUE TITLE
Error: 'Oops! An error occured'

### ISSUE THREAD

**Issue by Cedric8888** [notebooks-ai/notebooks-help#61]
When I try to open a project a get this error message.
A few hours a go there were no problems and now I get this message...

![2020-07-10_19-48-52](https://user-images.githubusercontent.com/68123907/87183438-70dcb300-c2e6-11ea-8ddf-8e78dec318be.png)

Any idea why?

**Comment by martinzugnoni** [comment]
Is this still happening? You should be able to run 3 projects in parallel without any issues.
