### ISSUE TITLE
Unable to fork the project from RMOTR curriculum, notebook.ai

### ISSUE THREAD

**Issue by ankur-morbale** [notebooks-ai/notebooks-help#64]
Hi Santiago,

While i was watching your tutorial "Intro to Data Analysis" on YouTube, I have been trying to access the notebook on notebook.ai unable to fork them. Please help. 

Thank You,
Ankur

**Comment by ankur-morbale** [comment]
![image](https://user-images.githubusercontent.com/28263888/88487491-7d524400-cf53-11ea-9c74-5c8fa2ef9939.png)

**Comment by wcj365** [comment]
same happened to me  today and still not working.

**Comment by martinzugnoni** [comment]
Can you please provide the URL of the project you are trying to access? I've just checked and the platform seems to be working as normal overall.

**Comment by wcj365** [comment]
The site started workin last night.
This is the project site:
https://notebooks.ai/wcj365/misc_projects
Not just one project, I tried several projects, and they all had the same issue.
No they are all good. 
Thank you!

**Comment by wcj365** [comment]
BTW, THere is a noticable performance degrade even it all works. The opening of a project takes longer.

**Comment by martinzugnoni** [comment]
Can you check again now and confirm me if the issue persists? I think I found the reason of the performance degrade, which should be fixed now. Thank you for reporting.

**Comment by wcj365** [comment]
Yes, the performance issue is resolved. 
Thank you!

**Comment by ankur-morbale** [comment]
Hi Martin,

It’s working now. Thank you so much. Have a great day!

Best regards,
Ankur
