### ISSUE TITLE
Unable to open project today

### ISSUE THREAD

**Issue by wcj365** [notebooks-ai/notebooks-help#65]
Hi, 
I have been enjoying using notebooks.ai on regular basi for about a year and realliy enjoy it.
I had no issue using it yesterday bit today I am not able to open my project. It failed at the last step of openning Jupyter notebook as the screen indicates.
Thanks!
Jay

**Comment by martinzugnoni** [comment]
Can you please check again now and tell me if it's fixed? thank you for reporting.

**Comment by wcj365** [comment]
Everything works as usual now. Thank you so much!
