### ISSUE TITLE
Experiencing the same "Oops! An error occured" error

### ISSUE THREAD

**Issue by wcj365** [notebooks-ai/notebooks-help#66]
Hi, 
I just experienced the same error on several projects after one of my project open successfully.
Looks like the issue is project specific?
This project did not open:
https://notebooks.ai/wcj365/lesson2/lab
This one opened:
https://notebooks.ai/wcj365/misc_projects/lab
Jay

**Comment by martinzugnoni** [comment]
Yes, that's temporarily expected. We've been under attack during the weekend, and we limited the amount of parallel running projects to a single one per user. We've just increased it to 3 per user. So now you will see that error after your 4th parallel project is turned on. We will try to normalize the situation as time goes by. Thank you for reporting.

**Comment by wcj365** [comment]
Thanks for the quick response.
Good to know the root cause. I will be more judicial in opening multiple
projects.
