### ISSUE TITLE
Failure to access notebooks, keeps kicking you out.

### ISSUE THREAD

**Issue by bassambarazi** [notebooks-ai/notebooks-help#73]
I have tried on both windows and mac machines to access notebooks from the dashboard but to no avail. The system fails to open any notebook and ends up at the home page of the website. I am able to sign into my account but that is all?

**Comment by JPL1** [comment]
I'm also finding this

**Comment by ck110162** [comment]
So am I.  There's no way to access notebook or sign up

**Comment by santiagobasulto** [comment]
Notebooks.ai is scheduled to shut down effectively October 1st. Sorry for the inconvenience. You can download all your files by that date.
