### ISSUE TITLE
Unable to sign up for Notebooks AI

### ISSUE THREAD

**Issue by yusingchan** [notebooks-ai/notebooks-help#75]
I am currently taking the Data Analysis with Python Course from FreeCodeCamp, I would like to follow along but it seems there's no longer an option to sign up for Notebooks AI?

**Comment by santiagobasulto** [comment]
No, sorry. Notebooks.ai is shutting down soon.

**Comment by lindawr** [comment]
Sorry to hear that.  Thank you for all your great work. :+1:

**Comment by bezzimo** [comment]
so shouldn't I approach this course for learning data analysis anymore? I just wanted to start it!
