### ISSUE TITLE
How can we download our data if we can't login?

### ISSUE THREAD

**Issue by JPL1** [notebooks-ai/notebooks-help#76]
Catch 22 situation
https://github.com/notebooks-ai/notebooks-help/issues/75

**Comment by santiagobasulto** [comment]
There's a SIGN IN button right at the top of the page.

<img width="1400" alt="Screen Shot 2020-09-15 at 10 39 35 AM" src="https://user-images.githubusercontent.com/872296/93217792-debab600-f73f-11ea-8356-5dd57d8cff44.png">

**Comment by JPL1** [comment]
Yes, but once logged in, on clicking into a project it logs you out again. Back to square 1

**Comment by santiagobasulto** [comment]
I am sorry, I didn't know about that issue. We don't see any other reports similar to that. Can you please clear your local storage / cookies and try again? Or with an incognito window.

**Comment by JPL1** [comment]
Seems to be a Firefox thing. I tried with Vivaldi and it worked. Thanks
