### ISSUE TITLE
Update Debian image to last stable (stretch)

### ISSUE THREAD

**Issue by dclong** [notebooks-ai/notebooks-help#9]
It seems to me that the Docker images are based on Debian Jessie which is too old. For example, sqlite3 fts5 is not available on it. Can we use a more up-to-date base image or allow user-define Docker image as suggested in https://github.com/rmotr/notebooks-help/issues/8?

**Comment by martinzugnoni** [comment]
Yes, Jessie is old but still supported and stable. Stretch (Debian 9) would probably be a better more-moderns still stable option. The newer versions (>9) are either in testing or still unstable. Check it here: https://en.wikipedia.org/wiki/Debian_version_history

**Comment by dclong** [comment]
Why not use Debian Stretch?

**Comment by santiagobasulto** [comment]
@dclong I'm marking this as a feature request. Thanks again for submitting it!

**Comment by santiagobasulto** [comment]
We need to decide if we should update or not. Scheduled for this sprint.

**Comment by dclong** [comment]
Any update on this issue?

**Comment by matiascaputti** [comment]
@dclong Docker images have been updated to use Debian Stretch (`python:3.6-stretch`).
